CREATE TABLE IF NOT EXISTS `customer_instances` (
  `id` int AUTO_INCREMENT NOT NULL,
  `purchaseId` int NOT NULL,
  `productId` int NOT NULL,
  `productVersionId` int,
  `customerId` int NOT NULL,
  `githubRepository` varchar(320),
  `githubCommit` varchar(80),
  `sourceChecksum` varchar(120),
  `vercelProjectId` varchar(120),
  `vercelDeploymentId` varchar(120),
  `databaseProvider` varchar(40),
  `databaseId` varchar(120),
  `domain` varchar(320),
  `instanceUrl` text,
  `adminUrl` text,
  `environment` enum('development','staging','production') NOT NULL DEFAULT 'production',
  `status` enum('creating','provisioning','deploying','health_checking','ready','degraded','failed','rolling_back','suspended','archived') NOT NULL DEFAULT 'creating',
  `healthStatus` enum('unknown','healthy','unhealthy') NOT NULL DEFAULT 'unknown',
  `lastError` text,
  `sagaStep` varchar(80),
  `metadata` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `customer_instances_id` PRIMARY KEY(`id`),
  CONSTRAINT `customer_instances_purchase_unique` UNIQUE(`purchaseId`)
);
