export const catalogSeed = [
  {
    slug: "atlas-studio",
    name: "Atlas Studio",
    tagline: "An editorial home for spaces that matter.",
    description: "A calm, image-led studio system for architects, interiors teams, and independent makers who want a site that feels as considered as their work.",
    category: "Studio / Architecture",
    price: "1280.00",
    currency: "EUR",
    status: "draft" as const,
    heroImage: "/assets/product-atlas.svg",
    demoUrl: null,
    requirements: "A domain, a hosting account, and your own brand assets.",
    license: "Single-project commercial license. One independent customer instance.",
    included: "Source code, responsive build, CMS-ready content model, deployment notes, handover checklist.",
    faq: "Q: Is Atlas Studio ready for a real client launch?\nA: The catalog product is a finished website system intended for an independent customer instance; final hosting, domain, and brand content remain part of setup.\n\nQ: What is included?\nA: Source code, responsive build, CMS-ready content model, deployment notes, and a handover checklist.\n\nQ: Can I customize it?\nA: Yes. The source is provided so the customer can adapt the system to their own brand and content.\n\nQ: What license is included?\nA: A single-project commercial license for one independent customer instance.",
    seoTitle: "Atlas Studio — Premium architecture website",
    seoDescription: "A cinematic, editorial website system for studios with a point of view.",
    features: [["Editorial layout system", "Long-form pages, project galleries, and considered typography out of the box."], ["Quiet motion language", "Scroll reveals and transitions that add rhythm without stealing attention."], ["Independent handover", "A self-contained customer instance with clear setup documentation."]],
    tech: ["React", "TypeScript", "Tailwind CSS", "Vite", "Content-ready"],
  },
  {
    slug: "signal-ops",
    name: "Signal Ops",
    tagline: "Make complex work legible.",
    description: "A dark, operational interface for teams who need to turn systems, metrics, and decisions into a clear daily rhythm.",
    category: "Operations / SaaS",
    price: "1640.00",
    currency: "EUR",
    status: "draft" as const,
    heroImage: "/assets/product-signal.svg",
    demoUrl: null,
    requirements: "A domain, a hosting account, and a product or service to explain.",
    license: "Single-project commercial license. One independent customer instance.",
    included: "Source code, dashboard shell, responsive states, access model notes, deployment notes.",
    faq: "Q: Who is Signal Ops for?\nA: It is designed for teams that need a clear operational website surface for products, metrics, and complex work.\n\nQ: What is included?\nA: Source code, dashboard shell, responsive states, access model notes, and deployment notes.\n\nQ: Can the interface be customized?\nA: Yes. The source is included for customer-led customization.\n\nQ: What license is included?\nA: A single-project commercial license for one independent customer instance.",
    seoTitle: "Signal Ops — Operational website system",
    seoDescription: "A dark, precise website system for modern operations and software teams.",
    features: [["Systems-first information design", "Turn dense product value into a sequence people can understand."], ["Responsive command layer", "A layout that remains composed from wide screens to compact phones."], ["Conversion-ready surfaces", "Pricing, proof, and product detail designed to move visitors forward."]],
    tech: ["React", "TypeScript", "Tailwind CSS", "Charts-ready", "Accessible"],
  },
  {
    slug: "mono-portfolio",
    name: "Mono Portfolio",
    tagline: "Less noise. More signal.",
    description: "A minimal portfolio framework built to let your craft lead, with a high-contrast visual system and a deliberate publishing rhythm.",
    category: "Portfolio / Creative",
    price: "890.00",
    currency: "EUR",
    status: "draft" as const,
    heroImage: "/assets/product-mono.svg",
    demoUrl: null,
    requirements: "A domain, a hosting account, and a clear body of work.",
    license: "Single-project commercial license. One independent customer instance.",
    included: "Source code, project archive, contact flow, responsive system, documentation.",
    faq: "Q: Who is Mono Portfolio for?\nA: It is a focused portfolio framework for people who want their work to lead the experience.\n\nQ: What is included?\nA: Source code, project archive, contact flow, responsive system, and documentation.\n\nQ: Is it mobile-ready?\nA: Yes. The system is designed mobile-first with responsive layouts.\n\nQ: What license is included?\nA: A single-project commercial license for one independent customer instance.",
    seoTitle: "Mono Portfolio — Minimal creative portfolio",
    seoDescription: "A focused portfolio system for people doing thoughtful work.",
    features: [["High-contrast canvas", "A confident monochrome base with one electric accent for focus."], ["Project-led navigation", "Visitors get to the work quickly, without a maze of menu layers."], ["Fast by default", "A lean front end designed to load with intention, not decoration."]],
    tech: ["React", "TypeScript", "Tailwind CSS", "SEO-ready", "Mobile-first"],
  },
] as const;

export type CatalogSeed = (typeof catalogSeed)[number];


export const categorySeed = [
  { slug: "studio-architecture", name: "Studio / Architecture", description: "Editorial systems for spaces, studios, and built work.", sortOrder: 10 },
  { slug: "operations-saas", name: "Operations / SaaS", description: "Clear digital surfaces for products, teams, and complex work.", sortOrder: 20 },
  { slug: "portfolio-creative", name: "Portfolio / Creative", description: "Focused systems for makers, artists, and independent practices.", sortOrder: 30 },
  { slug: "ecommerce", name: "E-commerce", description: "Product-led storefronts and conversion-ready commerce surfaces.", sortOrder: 40 },
  { slug: "business", name: "Business", description: "Confident digital foundations for modern businesses.", sortOrder: 50 },
  { slug: "agency", name: "Agency", description: "Showcases for teams with a point of view and a body of work.", sortOrder: 60 },
  { slug: "real-estate", name: "Real Estate", description: "Editorial and inventory systems for property and place.", sortOrder: 70 },
  { slug: "dashboard", name: "Dashboard", description: "Operational interfaces for data, workflow, and decisions.", sortOrder: 80 },
] as const;
